service: beer-to-me-api
provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221

functions:
    graphql:
        handler: build/src/adapters/inbound/graphql/handler.graphqlHandler
        name: graphql-beer-to-me-api
        events:
            - http:
                  path: graphql
                  method: post
                  cors:
                      origin: '*'

package:
    include: build/**
